apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: tomcat
      labels:
        app: nginx
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080